### ISSUE TITLE
MinMaxScaler from training data is not used to normalize the test data

### ISSUE THREAD

**Issue by dacb** [yiwen26/WindChaser#1]
https://github.com/yiwen26/WindChaser/blob/master/WindChaserModules/RecurrentNeuralNetwork/RNN_5Input/RNN_5input_XXJ.ipynb

**Comment by chennnnnyize-zz** [comment]
Actually this can be regarded as Minmax normalization: https://www.quora.com/What-is-the-meaning-of-min-max-normalization
